version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myb-nicehash-balance"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1234example"
s3_prefix = "myb-nicehash-balance"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
